### ISSUE TITLE
Uncaught Error: Call to a member function reset_structure() 

### ISSUE THREAD

**Issue by wesleycgmartins** [CherryFramework/CherryFramework#65]
Hello,

The plugin is presenting a flaw that is preventing the opening and editing of widgets in Wordpress, below are details of the error, if you can help me I would be very grateful.

Worpress 5.8 - Cherry Sidebars (version1.1.3) PHP version 7.3.29

Error Details:

Um erro do tipo E_ERROR foi causado na linha 404 do arquivo /home2/parten98/public_html/wp-content/plugins/cherry-sidebars/cherry-framework/modules/cherry-widget-factory/inc/class-cherry-abstract-widget.php. Mensagem de erro: Uncaught Error: Call to a member function reset_structure() on null in /home2/parten98/public_html/wp-content/plugins/cherry-sidebars/cherry-framework/modules/cherry-widget-factory/inc/class-cherry-abstract-widget.php:404
Stack trace:
#0 /home2/parten98/public_html/wp-includes/class-wp-widget.php(534): Cherry_Abstract_Widget->form(Array)
#1 /home2/parten98/public_html/wp-includes/widgets.php(2004): WP_Widget->form_callback(Array)
#2 /home2/parten98/public_html/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php(634): wp_render_widget_control('teddyacademy_wi...')
#3 /home2/parten98/public_html/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php(122): WP_REST_Widgets_Controller->prepare_item_for_response(Array, Object(WP_REST_Request))
#4 /home2/parten98/public_html/wp-includes/rest-api/class-wp-rest-server.php(1140): WP_REST_Widgets_Controller->get_items(Object(WP_REST_Request))
#5 /home2/parten98/public_html/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->r

**Comment by arnekeller** [comment]
@wesleycgmartins  try installing the Plugin **Classic Widgets**
[https://wordpress.org/plugins/classic-widgets/](https://wordpress.org/plugins/classic-widgets/)
